/**
 * RESTO-AI PRO: SYNC ENGINE
 * Updated to handle Pre-Calculated PHP Data
 */

const BRIDGE_URL = "https://managment.lovestoblog.com/api_sales.php"; 

window.onload = async () => {
    const urlParams = new URLSearchParams(window.location.search);
    const clientId = urlParams.get('client_id') || "51794";
    document.getElementById('display-id').innerText = clientId;
    fetchData(clientId);
};

async function fetchData(id) {
    const aiBox = document.getElementById('aiResponse');
    try {
        // Fetching the new "All-in-One" response from PHP
        const response = await fetch(`${BRIDGE_URL}?client_id=${id}`);
        const data = await response.json();
        
        if (data && data.orders) {
            // 1. Update Revenue Stats (using pre-calculated values from PHP)
            document.getElementById('total-revenue').innerText = `₹${data.revenue.toLocaleString('en-IN')}`;
            document.getElementById('total-orders').innerText = data.count;
            
            const avg = data.count > 0 ? (data.revenue / data.count) : 0;
            document.getElementById('avg-ticket').innerText = `₹${Math.round(avg)}`;

            // 2. Display the AI Insights already generated by PHP
            aiBox.innerHTML = data.ai_insights.replace(/\n/g, "<br>");

            // 3. Render the Graph
            renderChart(data.orders);
        } else {
            aiBox.innerText = "Data received, but no orders found.";
        }
    } catch (err) {
        console.error("Fetch error:", err);
        aiBox.innerHTML = `
            <div style="border:1px solid #ff4d4d; padding:10px; border-radius:10px;">
                <b>Sync Blocked!</b><br>
                Please open <a href="${BRIDGE_URL}?client_id=${id}" target="_blank" style="color:#007AFF;">This Link</a> 
                to authorize the connection, then refresh this page.
            </div>`;
    }
}

function renderChart(orders) {
    const ctx = document.getElementById('salesChart').getContext('2d');
    const sorted = [...orders].sort((a,b) => new Date(a.order_date) - new Date(b.order_date));
    
    new Chart(ctx, {
        type: 'line',
        data: {
            labels: sorted.map(r => r.order_date.split(' ')[0]),
            datasets: [{
                label: 'Revenue',
                data: sorted.map(r => r.total_amount),
                borderColor: '#007AFF',
                backgroundColor: 'rgba(0, 122, 255, 0.1)',
                fill: true,
                tension: 0.4
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: { legend: { display: false } }
        }
    });
}
